GET http://127.0.0.1:8000/api/unites
#GET http://127.0.0.1:8000/api/interventions
Authorization: Bearer WTG-SECRET-KEY-2026

#### Déclarer une nouvelle panne (POST)
#POST http://127.0.0.1:8000/api/interventions
#Authorization: Bearer WTG-SECRET-KEY-2026
#Content-Type: application/json
#
#{
#    "type": "Maintenance",
#    "etat": "OK",
#    "description": "Maintenance.",
#    "dateDebut": "15/03/2026 08:00:00",
#    "dateFin": "16/03/2026 08:00:00",
#    "unites_affectees": [6, 7]
#}
